-- ADICIONAR CÓDIGO POSTAL E LOCALIDADE AOS CLIENTES
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS postal_code text;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS city text;

-- ADICIONAR CÓDIGO POSTAL E LOCALIDADE AOS ORÇAMENTOS (HISTÓRICO)
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_postal_code text;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS client_city text;
